// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Wraith")>]
[<assembly: AssemblyProductAttribute("Wraith")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-07-05T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","ffa5869a85db9f4bfd0792dd73dbca4f7bdb6f1c")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Wraith"
    let [<Literal>] AssemblyProduct = "Wraith"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-07-05T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "ffa5869a85db9f4bfd0792dd73dbca4f7bdb6f1c"
