// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Wraith")>]
[<assembly: AssemblyProductAttribute("Wraith")>]
[<assembly: AssemblyVersionAttribute("0.3.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-10-18T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.3.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.3.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","cf89ab4cc67d188b891824b34548fd7c3af5a3af")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Wraith"
    let [<Literal>] AssemblyProduct = "Wraith"
    let [<Literal>] AssemblyVersion = "0.3.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-10-18T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.3.0"
    let [<Literal>] AssemblyInformationalVersion = "0.3.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "cf89ab4cc67d188b891824b34548fd7c3af5a3af"
